# Generated by Django 4.0.6 on 2022-07-17 22:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('dt_nascimento', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=60)),
                ('celular', models.CharField(max_length=14)),
                ('senha', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('numero_conta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='banco.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_transferencia', models.FloatField()),
                ('data_transferencia', models.DateTimeField(auto_now_add=True)),
                ('conta_destino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta_destino', to='banco.conta')),
                ('conta_origem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta_origem', to='banco.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField(default=datetime.date.today)),
                ('conta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta', to='banco.conta')),
                ('movimentacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao', to='banco.transferencia')),
            ],
        ),
    ]
