# Generated by Django 4.0.6 on 2022-07-17 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_alter_extrato_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrato',
            name='conta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banco.conta'),
        ),
        migrations.AlterField(
            model_name='extrato',
            name='movimentacao',
            field=models.FloatField(),
        ),
    ]
